### PR TITLE
Fix host

### LINKED ISSUE #56: Author fields host and displayName not being set
When new authors are created, the fields `host` and `displayName` are not being set.

### PR DESCRIPTION
**Pull request by gneagu**
Added host to author model. (Had to add after signup form is posted, but before it is saved).

### CODE REVIEW

**Comment by JohnDoeMask** [comment]
According to issue #56 , we also need to set displayName when new user are created. Could you please change it as well?

**Comment by gneagu** [comment]
DisplayName is now set on login. Fixes #56

**Comment by willfenton** [comment]
Looks good to me, we can probably merge this.

**Comment by gneagu** [comment]
> Looks good to me, we can probably merge this.

Thank Will. Merging now.

**Pull request merged**
