### PR TITLE
add document to the posts/view.py and profiles/view.py

### PR DESCRIPTION
**Pull request by XiaoleZ**

### CODE REVIEW

**Comment by JohnDoeMask** [comment]
We may have some merge conflicts, can you please do my code review? @XiaoleZ

**Comment by XiaoleZ** [comment]
> We may have some merge conflicts, can you please do my code review? @XiaoleZ

@JohnDoeMask  Just viewed

**Comment by JohnDoeMask** [comment]
I renamed the allthejs.js to post.js and put my js code there, but I noticed that you creates a posts_view.js in this pr? Should I put my js code in yours or mine?

**Comment by XiaoleZ** [comment]
> I renamed the allthejs.js to post.js and put my js code there, but I noticed that you creates a posts_view.js in this pr? Should I put my js code in yours or mine?

yours will be ok

**Pull request merged**
